application: helloworld
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

- url: /assets/stylesheets
  static_dir: stylesheets

- url: /assets/scripts
  static_dir: scripts

- url: /assets/images
  static_dir: images

- url: /templates/authorized/.*
  script: _go_app
  login: required
  auth_fail_action: redirect

- url: /templates/admin/.*
  script: _go_app
  login: admin
  auth_fail_action: redirect

- url: /.*
  script: _go_app

pagespeed:
domains_to_rewrite:
- www.foo.com
enabled_rewriters:
- MinifyCss
